### ISSUE TITLE
REM unit support?

### ISSUE THREAD

**Issue by djmtype** [MartijnCuppens/postcss-rfs#1]
Is this postcss version up to date with your [Sass version](https://github.com/MartijnCuppens/rfs) which seems to support REM sizes? Seems to return PX only.

```css

/* input */
responsive-font-size: 6.2rem;

/* output */
h1 {
  font-size: 99.2px;
}
@media (max-width: 1200px) {
  h1 {
    font-size: calc(31.04px + 5.68vw);
  }
}
```

I've also used this feature from Rucksack, but only had luck with PX sizes. With Rucksack it would return REM, but the responsive sizes was off. But, I'm getting off topic….
